# Generated by Django 5.0.14 on 2026-07-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="currency",
        ),
        migrations.AddField(
            model_name="walletprofile",
            name="currency",
            field=models.CharField(default="EUR", max_length=3),
        ),
    ]
