# Generated by Django 5.0.14 on 2026-08-11 07:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_idempotencykey_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nickname", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiary_of",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["nickname"],
            },
        ),
        migrations.AddConstraint(
            model_name="beneficiary",
            constraint=models.UniqueConstraint(
                fields=("owner", "target_wallet"),
                name="unique_beneficiary_per_owner_wallet",
            ),
        ),
    ]
