# Generated by Django 5.0.14 on 2026-08-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0005_beneficiary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="daily_transfer_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
