# Generated by Django 5.0.14 on 2026-07-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("COMPLETED", "Completed"),
                    ("PENDING", "Pending"),
                    ("FAILED", "Failed"),
                ],
                default="COMPLETED",
                max_length=10,
            ),
        ),
    ]
