# Generated by Django 5.0.14 on 2026-07-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0002_transaction_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="failure_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
