# Generated by Django 5.0.14 on 2026-07-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0003_transaction_failure_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="category",
            field=models.CharField(
                choices=[
                    ("UTILITIES", "Utilities"),
                    ("TELECOM", "Telecom & Internet"),
                    ("TV", "Television"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=10,
            ),
        ),
    ]
